### ISSUE TITLE
Can't reproduce the result in the article

### ISSUE THREAD

**Issue by fyx18** [Amit-P89/-DRackSim#1]
Hi, I was reproducing your work and found that for multiple workloads such as HPCG, XSBench and StreamCluster, with either all local memory or all remote memory (latency 300ns) configurations, and varying different remote memory latencies, The CPI(we guess is the performance indicator) is basically the same. We are not sure what is wrong. Can you help? Thank you,.

**Comment by Amit-P89** [comment]
Hi....happy to know that you are using this tool. I guess you are using the Detailed model where you can get the IPC in the results file.

I just tried with the exactly same set of workloads, but I got very different IPC for all three of them.

I used the following scripts to run the OMP versions of workloads and ran all of them with single-node and single memory pool configuration one by one for 50M instructions. The local and remote memory is allocated at a ratio of 50:50 in all cases. I am using the default parameters as uploaded in this repo.

OMP_NUM_THREADS=4 ../../../pin -t obj-intel64/Ins_Tracer.so -T 0 -N 1 -- ./sc_omp 10 20 256 65536 65536 1000 none output.txt 8 &
OMP_NUM_THREADS=4 ../../../pin -t obj-intel64/Ins_Tracer.so -T 0 -N 2 -- ./xhpcg &
OMP_NUM_THREADS=4 ../../../pin -t obj-intel64/Ins_Tracer.so -T 1 -N 4 -- ./XSBench -s small -t 4 &


One thing I am not sure of is how did you configure the remoe latency to 300ns as the remote latency calculation is dependt on multiple factors as mentioned in the interconnect file, it is mentioned in CPU cycles there.

Please make sure that you are writing results to different directory for all these workloads as it may not overwrite the previous ones (have to verify).

If you find any issue, I am happy to help if you share some more detials. The scripts that you used and other parameters that you have changed.

**Comment by Amit-P89** [comment]
Hiii...happy to know that you are using this tool. I guess you tried the detailed model where you can see the IPC in the results file. I tried all of three workloads mentioned by you and got very different IPC for all of them.

I run all of them in single-node and single memory pool configuration one by one for the first 50M instructions each.  

I used the folliwng scripts for instrumentation by PIN and all the parameters are set as default that are there in the github repo. Default parameters use local and remote memory allocation at the ratio of 50:50. 

OMP_NUM_THREADS=4 ../../../pin -t obj-intel64/Ins_Tracer.so -T 0 -N 1 -- ./sc_omp 10 20 256 65536 65536 1000 none output.txt 8 &
OMP_NUM_THREADS=4 ../../../pin -t obj-intel64/Ins_Tracer.so -T 0 -N 2 -- ./xhpcg &
OMP_NUM_THREADS=4 ../../../pin -t obj-intel64/Ins_Tracer.so -T 1 -N 4 -- ./XSBench -s small -t 4 &



One thing I am not sure of is how you changed the remote latency to 300ns, as there are multiple parameters which control the remote latency. These are mentioned in **_interconnect.cpp_** in the form of CPU cycles rather than in nanoseconds. Also use a different results directory name (that does not already exist) when running the simulator as it may not overwrite the content of existing files in that directory (have to verify).

I also run it with 100% local memory and the results generated are different than the previous case. This difference would depend on the number of remote memory requests and the average remote memory access time. More the remote memory requests (memory bound workload) more the difference in IPC. Similarily, more the remote memory access time (depends on parameters in interconnect.cpp), more will be the difference in results on changing local/remote allocation ratio.

I will be happy to help if I get more details about the parameters used.

**Comment by fyx18** [comment]
Thank you for your answer. For the 300ns/250ns latency, we change the following command in **_interconnect.cpp_** and confirm the latency in _**node_0result.txt**_ (Node avg local access time: 39.04(ns), Node avg remote access time: 254.42(ns))
#define nic_proc_delay (4 * 5) //freq_ratio->5
#define switch_proc_delay (4 * 15)//freq_ratio->15
#define prop_delay (5*CPU_Freq) // max 1-meter inside rack
#define switching_delay (1 * 5)//freq_ratio->5

However, for XSBench workload, 1. the result of the **_100% local memory_** configuration is:
Total Issued instructions: 4761825
Simulated Cycles on core: 399874483
core local memory access: 118681
core remote memory access: 0
avg local access time(ns): 117.89
avg remote access time(ns): -nan
 **CPI is: 83.98**
2. the result of the **_100% remote memory_** configuration is:
Total Issued instructions: 4999899
Simulated Cycles on core: 420789508
core local memory access: 0
core remote memory access: 82023
avg local access time(ns): -nan
avg remote access time(ns): 311.34
 **CPI is: 84.16**

That is to say, the result of 100% local or 100% remote is alomost the same. In addition, we changed the core numbers from 4 to 1, and tried other workload, but the result is same. Where might there be a problem? Thank you!

**Comment by Amit-P89** [comment]
Hi...the way you are running it is correct. But the number of simulated cycles on the core are way off the mark. It should not be this high for such a small number of instruction. That is why the difference is very less in your results. 

Another reason is the number of memory accesses are also very less in this workload and have a small impact on the ipc/cpi.

But in your case, first reason is more true. Make sure you delete the shared memory variables before you start the simulation again with a same "node number". 

If problem presists, I am.open for a quick google meet.

Thanks.

**Comment by Amit-P89** [comment]
I had faced this before. The only reason I could say is due to mixing up of shared memory variables. You can check with 'ipcs' if any older variable is still alive. **bash clear_sm.sh** does the work nost of the time. If possible restart your system once as it would clear all temporary variables and then do a fresh simulation.

I do face this issue sometimes after large number of simulations...if I forget to do use clear_sm.sh in between.

**Comment by fyx18** [comment]
Thank you for your advice. I check the older variable and use clear_sm.sh in between, the result didn't change any way... Can you share some data of Node0result.txt (XSBench) and we can find the problem by comparison. Thanks!

**Comment by fyx18** [comment]
Thank you for your help. We solve the problem successfully.

**Comment by Amit-P89** [comment]
Hi....that's good to know that the issue is solved.

BTW, results for XSBench on 4-core after 50M instructions look like this with 50:50 local/remote.

					----------------Node 0 Overall Statistics---------------
Total Issued instructions: 					50000227
Total executed instructions: 					50000098
Total committed instructions: 					50000006
IPC is: 							1.52
CPI is: 							0.66
L3 cache demand accesses: 					1508286
L3 cache demand hits:     					470452
L3 cache demand misses:   					1037750
L3 cache hit rate: 						31.19
Write-backs LLC : 						752
Total Load-stores by CPU: 					14341228
Non-redundant Load-stores					14265895
LLC to memory requests: 					1037921
Overall Miss Rate : 						7.28
Total local memory accesses sent: 				520460
Total local memory reads completed:    				520284
Total local memory writebacks completed:    			176
Total local memory accesses completed: 				520460
Total remote memory accesses sent: 				518040
Total remote memory reads completed:    			517461
Total remote memory writebacks completed:    			576
Total remote memory accesses completed:   			518037
Total memory accesses: 						1037921
Node avg local access time:					42.86(ns)
Node avg remote access time:					138.76(ns)
Node avg remote access time (excluding network):		42.43(ns)
Average memory access time  :				90.67(ns)
